metadata:
  creationTimestamp: null
  name: podinfo
  namespace: ocm-system
spec:
  component:
    name: mpas.ocm.software/podinfo
    registry:
      url: ghcr.io/skarlso/mpas
    version: 1.0.1
  pipelines:
  - configuration:
      rules:
        name: ""
        version: ""
      valuesFile:
        path: ""
    localization:
      rules:
        name: config
        version: 1.0.0
    name: backend
    resource:
      name: manifests
      version: 1.0.0
    targetRole:
      selector:
        matchLabels:
          target.mpas.ocm.software/ingress-enabled: "true"
      type: kubernetes
  - configuration:
      rules:
        name: ""
        version: ""
      valuesFile:
        path: ""
    localization:
      rules:
        name: config
        version: 1.0.0
    name: frontend
    resource:
      name: manifests
      version: 1.0.0
    targetRole:
      selector:
        matchLabels:
          target.mpas.ocm.software/ingress-enabled: "true"
      type: kubernetes
  - configuration:
      rules:
        name: ""
        version: ""
      valuesFile:
        path: ""
    localization:
      rules:
        name: config
        version: 1.0.0
    name: cache
    resource:
      name: manifests
      version: 1.0.0
    targetRole:
      selector:
        matchLabels:
          target.mpas.ocm.software/ingress-enabled: "true"
      type: kubernetes
status: {}
